name: binder_env
channels:
  - conda-forge
dependencies:
  - cartopy=0.21.1
  - pip
  - pip:
    - numpy==1.24.2
    - pandas==1.5.3
    - netCDF4==1.6.3
    - xarray==2023.3.0
    - solara==1.19.0
    - ipywidgets==8.0.6
    - matplotlib==3.6.3
    - watermark==2.4.3
    - python-wget==3.2
