name: binder_env
channels:
  - conda-forge
dependencies:
  - cartopy=0.21.1
  - pip
  - pip:
    - nbgitpuller
    - numpy==1.24.2
    - xarray==2023.3.0
    - solara==1.19.0
    - ipywidgets==8.0.6
    - matplotlib==3.6.3
    - watermark==2.4.3
    - wget==3.2
