name: binder_env
channels:
  - conda-forge
dependencies:
  - cartopy=0.24.0
  - pip
  - pip:
    - nbgitpuller
    - numpy==2.2.4
    - xarray==2025.3.1
    - solara==1.39.0
    - ipywidgets==8.1.6
    - matplotlib==3.9.4
    - watermark==2.5.0
    - wget==3.2