name: binder_env
channels:
  - conda-forge
dependencies:
  - python==3.11.12
  - cartopy==0.24.0
  - numpy==2.2.4
  - xarray==2025.3.1
  - netcdf4==1.7.2
  - scipy==1.15.2
  - ipywidgets==8.1.6
  - matplotlib==3.9.4
  - watermark==2.5.0
  - wget==3.2
  - pip
  - pip:
    - nbgitpuller
    - solara==1.39.0
